/**
 * Verification Code Service
 *
 * In-memory storage for 6-digit verification codes used in the
 * password change flow. Codes expire after 10 minutes.
 *
 * Design decision: In-memory Map is sufficient for single-admin panel.
 * See design.md for rationale.
 *
 * SCALING LIMITATION: this store is process-local, so it is NOT
 * horizontally scalable. On multi-instance deployments the code generated by
 * instance A is invisible to instance B (and vice versa), so a code requested
 * through one instance cannot be validated through another. If the service is
 * ever scaled out, replace this Map with a shared store (Redis with TTL) or a
 * DB-backed table. The strict auth limiter (5 tries/15 min per IP) mitigates
 * brute-forcing the 6-digit code in the meantime.
 */

import { randomInt } from 'node:crypto';
import { ValidationError } from '../utils/errors.js';

interface VerificationCodeEntry {
  code: string;
  expiresAt: Date;
  used: boolean;
}

class VerificationCodeService {
  private store = new Map<string, VerificationCodeEntry>();

  /**
   * Generate a 6-digit verification code for a user.
   * Overwrites any previous unexpired code for the same user.
   */
  generate(userId: string): { code: string; expiresIn: number } {
    // CSPRNG source: crypto.randomInt (never Math.random — predictable codes
    // would allow brute-forcing the password-change flow).
    const code = randomInt(0, 1000000).toString().padStart(6, '0');
    const expiresIn = 10 * 60; // 10 minutes in seconds

    this.store.set(userId, {
      code,
      expiresAt: new Date(Date.now() + expiresIn * 1000),
      used: false,
    });

    return { code, expiresIn };
  }

  /**
   * Validate a verification code for a user.
   * Throws ValidationError (HTTP 400) for each failure mode — never a 500.
   */
  validate(userId: string, code: string): void {
    const entry = this.store.get(userId);

    if (!entry) {
      throw new ValidationError('No verification code found. Please request a new code.');
    }

    if (entry.used) {
      throw new ValidationError('This verification code has already been used.');
    }

    if (new Date() > entry.expiresAt) {
      this.store.delete(userId);
      throw new ValidationError('Verification code has expired. Please request a new code.');
    }

    if (entry.code !== code) {
      throw new ValidationError('Invalid verification code.');
    }

    // Mark as used (single-use)
    entry.used = true;
  }

  /**
   * Get the number of stored codes (for testing/debugging).
   */
  get size(): number {
    return this.store.size;
  }
}

// Singleton instance
export const verificationCodeService = new VerificationCodeService();
